version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "monthly"
    versioning-strategy: widen
    groups:
      symfony:
        patterns:
          - "symfony*"
    labels:
      - "RFR"
      - "dependencies"
