name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version:
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
      - name: Install dependencies
        run: |
          composer install
      - name: PHPUnit tests
        run: |
          vendor/bin/phpunit

  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
      - name: Install dependencies
        run: |
          composer install
      - name: PHP_CodeSniffer
        uses: chekalsky/phpcs-action@v1
        with:
          phpcs_bin_path: './vendor/bin/phpcs'

  phpmd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
      - name: Install dependencies
        run: |
          composer install
      - name: PHP Mess Detector
        run: |
          vendor/bin/phpmd src text phpmd.xml

  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
      - name: Install dependencies
        run: |
          composer install
      - name: PHPStan
        run: |
          vendor/bin/phpstan analyse --level=max src tests
