name: Security checks - Github Action

on:
  pull_request:
    paths: [.github/workflows/**]

jobs:
  ci_harden_security:
    name: Ensure SHA pinned actions
    runs-on: ubuntu-latest
    steps:
      - name: Fetch lastest changes
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # renovate: tag=v3.0.0
      - name: Ensure SHA pinned actions
        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@a397475397837fb57396bd18f09d991625e604fe # renovate: tag=v1.2.0
